### ISSUE TITLE
[User-Story]: Weekly sprint cleanup

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#120]
### Description
Clean sprint after every week. Generate Sprint Status reports and analysis of last sprint as well start new sprint.
- After every **Sprint** ends Sprint backlog has to be refined.
- For all the Issue currently in backlog, Sprint iteration manually has to changed.

### Acceptance Criteria

- [ ] Sprint cleanup every week (End of each sprint)
- [ ] Generate sprint status report
- [ ] Start new sprint

### Decisions
- NA

### Subtask
- [ ] #129
