### ISSUE TITLE
User registration API

### ISSUE THREAD

**Issue by shubham-8551** [Arc-i-Tech/Arc-i-Tech.github.io#152]
## Task Summary
- User registration API using which user can be registered.
- API will accept all necessary json data for registration through HTTP request and return appropriate json response.

## Acceptance Criteria
- [x] API must accept data for registration
- [x] Registration with given data only.
- [x] Duplicate registration should not happen
- [x] Handle username (Auto generate/ Accept username), but it must be unique
- [x] Send response with success or failure status. 

## Subtasks
- NA.
  
## Related Issues
- NA

## Additional Notes
- Basic and necessary validation must be handled, _such as unique `username`_
