### ISSUE TITLE
[User-Story]: Update Existing Docs

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#167]
### Description
Update existing documents for,
- Corrections to remove ambiguity or to make it more clear and understandable.
- Add new steps/ guideline
- Update existing guideline to make it more precise.
- Add new terminologies

### Subtask
- [x] Pull Request Guidelines 
      - Close issue after merge
      - Draft Pull Request
      - PR Reviewer
      - Squash Commit
- [x] Branch creation guidelines 
      - Branches for task
      - Clear explanation with examples to branch codes/ types
      - Estimate: 3hr 
- [x] Commit guidelines
- [x] Readme for guidelines

**Comment by ajayg2808** [comment]
Closed by #174
