### ISSUE TITLE
User profile update api

### ISSUE THREAD

**Issue by ajstyle2410** [Arc-i-Tech/Arc-i-Tech.github.io#168]
## Task Summary
- Implement a back end API to update user profile.
- These updates can be personal info updates from profile.
- Accept response from authenticated user to update profile and provide appropriate response.

## Acceptance Criteria
- [ ] Only authenticated users are allowed to update profile.
- [ ] User allowed to updates his own profile, he must not able to update other users profile.
- [ ] Id or incremental fields can not be updated.

## Subtasks
- NA
  
## Related Issues
- NA

## Additional Notes
- Add validations similar to user registration.
