### ISSUE TITLE
[EPIC]: DevOps/ Project automation

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#199]
## DevOps/ Project automation
- Automate various repeated processes for productivity. 
- It includes DevOps as well as project related automation.
- Build new automation's or improve existing.

### Background/ Goals
- Reducing repeated manual process to bring uniformity.
- Automation are important to increases productivity as focusing more on actual work than worrying about process.

## Rollout plan
- Not bound to specific release, as improvements are always welcomed.

## User Stories
- [ ] #120

## Tasks
1. GitHub Project automation
   - [x] #200
   - [ ] Automation priorities
   - [x] Issue automation should not happen for closed issues.
   - [ ] Sync in Issue and PR automation
   - [ ] Review submitted action
   - [x] #204
   - [x] #205
   - [ ] Delete the branch when PR merges successfully.
   - [ ] Issue Reopened
   - [ ] No need to close an issue if PR is targeting the default branch
   - [ ] Update Workflow Diagram
   - [ ] Workflow from the default branch should always get executed.
   - [ ] Dependency graph for epic (If possible, for all)

2. Code
   - [ ] SonarQube - Code Coverage Report
   - [ ] Checkstyle action
 

### Later
- Build and Deploy automations

## Details
- This automation's are not only for GitHub project or for GitHub features rather automation's can be used throughout software development life cycle.
- Find out repeated manual processes and report it so we can bring it to automation.

## Success Metrics
- Reduction in manual processes in GitHub projects.

## Related Epics or Dependencies
- NA

## Additional Notes
- NA

**Comment by serv-cat** [comment]
Closed by #208
