### ISSUE TITLE
Task-Update Github project automation to handle Pull Requests

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#200]
## Task Summary
- Currently **Pull Requests** are being added to **GitHub Project: [Arc-i-Tech-website](https://github.com/orgs/Arc-i-Tech/projects/2)**.
- **Pull Requests** must not get added to any of the GitHub project and are not tracked through GitHub projects.
- For each Pull Request there should be at-least one **Closing Reference Issue** (Closing)
- According to Pull Request state and updates move linked issues/ track linked issues.

## Acceptance Criteria
- [x] Pull Request must not get added to GitHub project
- [x] Linked issue/ closing issues are moved according to PR state/ updates.
- [x] ~~Pull Request should have assignee as to linked/ closing issues.~~ Taken care by #204

## Subtasks
- NA
  
## Related Issues
- NA

## Additional Notes
- NA

**Comment by ajayg2808** [comment]
Closed by: #203
