### ISSUE TITLE
[User-Story]: User Update and Delete

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#211]
**As a `User`,**

**I want to `update my profile or request to delete my profile`,**

**so that `I can change or modify profile content as I want and can give up on my profile any time`.**

--- 

## Description
Users must able to update or request to delete its profile.
Make sure only authorized updates or delete happens. 

## Acceptance Criteria
- [ ] User is able to update its profile
- [ ] User is able to send delete request for its profile.
- [ ] Unauthorized update or delete request are forbidden.

## Definition of Done
- [ ] Code is implemented and reviewed.
- [ ] Tests (unit/integration) are written and passing.
- [ ] Documentation (if applicable) is updated.
- [ ] Deployed to staging/production and validated.

## Designs
- User update and delete tasks from #149 are moved here

## Decisions
- User updation and deletion tasks are moved here.

## Subtask
- [ ] #168
- [ ] #169
- [ ] #173

## Related Issues or Tasks
- #149
