### ISSUE TITLE
Setup a eclipse workspace

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#76]
- [x] Create empty maven project - dynamic web project.
- [x] Setup default eclipse settings for workspace.
- [x] Add required dependencies.
- [x] Update **README.md** -> Update required steps, required downloads, etc.
- [x] if any?
